# Generated by Django 5.0.1 on 2024-01-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='correo',
            new_name='email',
        ),
    ]
